# Theme: CLRS
# Light color scheme ported from the previous kitty configuration

# Default colors
[colors.primary]
background = '#ffffff'
foreground = '#262626'

[colors.cursor]
text   = '#ffffff'
cursor = '#6fd2fc'

[colors.selection]
text       = '#ffffff'
background = '#6fd2fc'

# Normal colors
[colors.normal]
black   = '#000000'
red     = '#f72729'
green   = '#32895c'
yellow  = '#f96f1c'
blue    = '#125ccf'
magenta = '#9f00bc'
cyan    = '#32c2c0'
white   = '#b2b2b2'

# Bright colors
[colors.bright]
black   = '#545753'
red     = '#fb0416'
green   = '#2cc631'
yellow  = '#fcd627'
blue    = '#156ffe'
magenta = '#e800b0'
cyan    = '#39d5ce'
white   = '#ededec'
