{ config, lib, ... }:

let
  inherit (config.networking) hostName;

  # All machines except this one — the local host already has a loopback
  # entry generated by NixOS for its own hostname.
  remoteMachines = lib.filterAttrs (name: _: name != hostName) config.machines;

  # Reachable addresses for a machine, dropping nulls and the iphone's
  # 0.0.0.0 placeholder.
  ipsFor = machine: lib.filter (ip: ip != null && ip != "0.0.0.0") [
    machine.ipv4
    machine.vpnIp
  ];
in
{
  imports = [ ./machines.nix ];

  # Resolve bare machine names (e.g. `ssh desktop`) from the central registry.
  # Each name maps to its LAN and VPN IP, so getaddrinfo/SSH try each in turn:
  # the host is reachable directly on the home network and over WireGuard when
  # away. This also covers ping, scp, curl, etc. — not just SSH.
  networking.hosts = lib.concatMapAttrs (
    name: machine: lib.genAttrs (ipsFor machine) (_ip: [ name ])
  ) remoteMachines;
}
