{ config, lib, ... }:

let
  inherit (config.networking) hostName;

  # All machines except this one — the local host already has a loopback
  # entry generated by NixOS for its own hostname.
  remoteMachines = lib.filterAttrs (name: _: name != hostName) config.machines;

  # Drops nulls and the iphone's 0.0.0.0 placeholder.
  isReachable = ip: ip != null && ip != "0.0.0.0";

  machinesWithVpnIp = lib.filterAttrs (_name: machine: isReachable machine.vpnIp) remoteMachines;
in
{
  imports = [ ./machines.nix ];

  # Resolve bare machine names (e.g. `ssh desktop`) from the central registry.
  # Each name maps to its LAN and its VPN address, so the host answers both on
  # the home network and over WireGuard when away. This covers ping, scp, curl,
  # etc. — not just SSH.
  #
  # Order matters and is the reason the two address families are split across
  # two options. getaddrinfo hands equal-scope IPv4 addresses to the caller in
  # /etc/hosts order, and a client such as ssh walks that list serially, so the
  # first address decides the normal case. NixOS emits `networking.hosts` (an
  # attribute set, hence sorted by key) first and appends `networking.extraHosts`
  # after it — putting both families in `networking.hosts` sorted "10.100.0.3"
  # ahead of "192.168.178.87" and sent every LAN connection through the tunnel
  # in Finland (94 ms instead of 4 ms), or made it hang for the full TCP timeout
  # whenever the tunnel was down. LAN first, VPN as the fallback.
  networking.hosts = lib.concatMapAttrs (
    name: machine: lib.optionalAttrs (isReachable machine.ipv4) { ${machine.ipv4} = [ name ]; }
  ) remoteMachines;

  networking.extraHosts = lib.concatMapStringsSep "\n" (
    name: "${machinesWithVpnIp.${name}.vpnIp} ${name}"
  ) (lib.attrNames machinesWithVpnIp);
}
